FROM php:7.3-fpm

RUN docker-php-ext-install pdo_mysql mysqli

RUN curl -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod a+x /usr/local/bin/wp


RUN apt-get update && apt-get install -y sudo less

# Cleanup
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
