version: "3"
services:
    web:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www
            - ./vhost.conf:/etc/nginx/conf.d/vhost.conf
        restart: always
        depends_on:
            - php
            - db
    php:
        image: php:7.3-fpm
        build:
            context: ./
            dockerfile: Dockerfile-php
        volumes:
            - ./www:/var/www
            - ./phpconf.ini:/usr/local/etc/php/conf.d/phpconf.ini
        depends_on:
            - db
        links:
            - db:mysql
    db:
        image: mysql:5.7
        ports:
            - "6033:3306"
        restart: always
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        volumes:
            - mysql_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8082:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
        restart: always
        depends_on:
            - db
volumes:
    mysql_data:
