FROM php:7.3-fpm

RUN apt-get update \
	&& apt-get install -y sudo less libz-dev libmemcached-dev \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN docker-php-ext-install pdo_mysql mysqli

#RUN pecl install memcached-3.1.3 \
#	&& pecl install xdebug-2.7.2 \
#	&& docker-php-ext-enable memcached xdebug

RUN curl -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod a+x /usr/local/bin/wp
